server:
  port: 4447

retrofit:
  baseUrl: http://localhost:4446/


  restServices:
    user_url: api/v1/auth/login
    acceptance_url: api/acceptances
    address_url: api/addresses
    adjustments_url: api/adjustments
    application_url: api/applications
    attribute_of_calculation_object_url: api/attribute_of_calculation_objects   #[]
    bank_account_url: api/bank_accounts
    bankAccount_url: api/bankAccounts   #404
    building_url: api/buildings
    call_url: api/calls
    city_url: api/cities
    company_url: api/companies
    commissioner_reports_url: api/commission_reports
    contract_url: api/contracts
    contractor_group_url: api/contractor_groups
    contractor_url: api/contractors
    country_url: api/countries
    currency_url: api/currencies
    customer_order_url: api/customer_orders   # []
    department_url: api/departments
    discount_url: api/discount
    employee_url: api/employees
    feed_url: api/feed
    image_url: api/images
    invoice_edit_url: api/invoice_edits   #404
    invoice_product_url: api/invoice_products   # []
    invoice_received_url: api/invoice_received
    invoice_url: api/invoices   # []
    language_url: api/language
    legal_detail_url: api/legal_details
    movement_url: api/movements   # []
    priceList_url: api/price_list   # []
    printing_documents_url: api/printing_documents
    payments_url: api/payments    #todo проверить связь с taskDto
    position_url: api/positions
    posting_url: api/posting
    product_group_url: api/product_groups
    product_url: api/products
    product_stage_url: api/production_stage
    production_tasks_url: api/production_tasks
    production_tasks_additional_field_url: api/additional_field
#    production_operations_url: api/productions_operations
    project_url: api/projects
    recycleBin_url: api/recycle_bin
    region_url: api/regions
    return_url: api/returns   # []
    retail_url: api/retail
    role_url: api/roles
    settings_url: api/settings
    start_screen_url: api/start_screen
    stats_url: api/stats
    street_url: api/streets
    subscription_url: api/subscription
    supplier_invoice_url: api/supplier_invoices
    tax_system_url: api/tax_systems
    type_of_contractor_url: api/type_of_contractors
    type_of_price_url: api/type_of_prices
    technological_map_url: api/technological_map
    technological_map_material_url: api/technological_map_material
    technological_map_group_url: api/technological_map_group
    unit_url: api/units
    units_of_measure_url: api/unitsOfMeasure
    writeOffs_url: /api/writeOffs
#    production_order_url: api/production_orders

    goods_to_realize_get_url: api/goodstorealizeget
    goods_to_realize_give_url: api/goodstorealizegive
    #    customer_order_url: api/customer_orders
    tasks_url: api/tasks_employee

    warehouse_url: api/warehouses
    sales_channels_url: api/sales_channels
    scripts_url: api/scripts
    shipments_url: api/rest_shipments
    internal_order-url: api/internal_orders
    documents_url: /api/documents

retrofit2:
  baseUrl: https://suggestions.dadata.ru/suggestions/

  restServices:
    inn_request: api/4_1/rs/suggest/party

  token: Token 2d713421aa060556bee478b15c284a9cdf05a6e5